name: Test webhook
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    # https://github.com/marketplace/actions/secure-github-webhook
